import argparse
import json
import os
import inspect
from typing import Dict, List

import gdown
import numpy as np
import pandas as pd
from datasets import load_dataset
from pydantic import BaseModel

TOP_K = 5
DATASET_ALIASES = {
    "loc-bench-v1": "czlll/Loc-Bench_V1",
    "loc-bench_v1": "czlll/Loc-Bench_V1",
    "locbench-v1": "czlll/Loc-Bench_V1",
    "locbench_v1": "czlll/Loc-Bench_V1",
}


def safe_mean(values: List[float]) -> float:
    return float(np.mean(values)) if values else 0.0


def safe_std(values: List[float]) -> float:
    return float(np.std(values)) if values else 0.0


def download_golden_data(
    artifact_dir: str, dataset: str, split: str = "test"
) -> pd.DataFrame:
    dataset_file = f"{dataset}_golden_stats.csv"
    dir = f"{artifact_dir}/assets"
    os.makedirs(dir, exist_ok=True)
    # Download the dataset file if not found
    # The dataset file are originally generated by dataset/parse_golden_patch.py, cached for convenience
    # Users wishing to regenerate the dataset file can run the script dataset/parse_golden_patch.py
    url_dict: Dict[str, str] = {
        "common_golden_stats.csv": "https://drive.google.com/file/d/1t0nl6LLq4WEVNHbasULLQ1onQQtxLL6A/view?usp=sharing",
        "lite_golden_stats.csv": "https://drive.google.com/file/d/1D9LWg78K66kHnex5RopBbTu_rwz1fhaS/view?usp=sharing",
        "verified_golden_stats.csv": "https://drive.google.com/file/d/1M6KZyLezU8ut0hrKUJBwi_TpvHV437NB/view?usp=sharing",
    }
    if dataset_file not in url_dict:
        hf_dataset = DATASET_ALIASES.get(dataset.lower(), dataset)
        print(f"Loading golden data from HF dataset {hf_dataset}/{split}")
        return pd.DataFrame(load_dataset(hf_dataset, split=split))

    url = url_dict[dataset_file]
    file_dir = f"{dir}/{dataset_file}"
    if not os.path.isfile(file_dir):
        print(f"Downloading {dataset_file} from google drive url {url}")
        download_kwargs = {"url": url, "output": file_dir, "quiet": False}
        if "fuzzy" in inspect.signature(gdown.download).parameters:
            download_kwargs["fuzzy"] = True
        gdown.download(**download_kwargs)
    return pd.read_csv(file_dir)


class DiffNode(BaseModel, frozen=True):
    node_name: str
    node_type: str
    lineno: int
    end_lineno: int

    def __repr__(self):
        return f"{self.node_type}:{self.node_name} {self.lineno}:{self.end_lineno}"


class SrcRange(BaseModel, frozen=True):
    lineno: int
    end_lineno: int
    is_pure_addition: bool
    is_global_addition: bool


class DiffLoc(BaseModel, frozen=True):
    file: str
    diff_nodes: List[DiffNode]
    lineno: int
    end_lineno: int

    def __repr__(self):
        return f"{self.file} {self.lineno}:{self.end_lineno}\n" + "\n".join(
            [
                f"    Node Level {i}: {repr(diff_node)}"
                for i, diff_node in enumerate(self.diff_nodes)
            ]
        )


class ParsedPatch(BaseModel):
    diff_locs: List[DiffLoc]

    def __repr__(self):
        return "\n".join(
            [
                f"Diff Loc {i} : {repr(diff_loc)}"
                for i, diff_loc in enumerate(self.diff_locs)
            ]
        )


def normalize_file_path(file_path: str) -> str:
    if file_path and file_path[0] == "/":
        return file_path[1:]
    return file_path


def unique_preserve_order(items: List[str]) -> List[str]:
    seen = set()
    ordered = []
    for item in items:
        if item and item not in seen:
            seen.add(item)
            ordered.append(item)
    return ordered


def top_k_scores(gt_set: set, model_ranked: List[str], k: int = TOP_K) -> tuple:
    model_top_k = unique_preserve_order(model_ranked)[:k]
    if not gt_set:
        empty_score = 1.0 if not model_top_k else 0.0
        return empty_score, empty_score

    hits = len(gt_set.intersection(model_top_k))
    acc = hits / min(len(gt_set), k)
    precision = hits / len(model_top_k) if model_top_k else 0.0
    f1 = 0.0 if precision + acc == 0 else 2 * precision * acc / (precision + acc)
    return acc, f1


def add_missing_top_k_scores(
    file_acc_at_5_list: List[float],
    file_f1_at_5_list: List[float],
    func_acc_at_5_list: List[float],
    func_f1_at_5_list: List[float],
) -> None:
    file_acc_at_5_list.append(0.0)
    file_f1_at_5_list.append(0.0)
    func_acc_at_5_list.append(0.0)
    func_f1_at_5_list.append(0.0)


def build_golden_sets(parsed_patch: ParsedPatch, inst_id: str) -> tuple:
    file_set = set()
    func_set = set()
    for diff_loc in parsed_patch.diff_locs:
        file_path = diff_loc.file
        file_set.add(file_path)
        diff_nodes = diff_loc.diff_nodes
        func_name = file_path + ":"
        if len(diff_nodes) == 0:
            continue
        func_name += diff_nodes[0].node_name
        if (
            len(diff_nodes) > 1
            and diff_nodes[0].node_type == "ClassDef"
            and diff_nodes[1].node_type == "FunctionDef"
        ):
            func_name += "." + diff_nodes[1].node_name
        elif len(diff_nodes) > 1 and diff_nodes[0].node_type != "FunctionDef":
            print("Weird diff_loc:", inst_id, diff_nodes)
            continue
        func_set.add(func_name)
    return file_set, func_set


def parse_locbench_func(func: str) -> tuple:
    file_path, _, func_name = func.partition(":")
    return normalize_file_path(file_path), func_name


def build_locbench_golden_sets(inst: pd.Series) -> tuple:
    file_set = set()
    func_set = set()
    edit_functions = inst.get("edit_functions", [])
    if isinstance(edit_functions, str):
        try:
            edit_functions = json.loads(edit_functions)
        except json.JSONDecodeError:
            edit_functions = [edit_functions]

    for func in edit_functions:
        if not func:
            continue
        file_path, func_name = parse_locbench_func(func)
        if file_path:
            file_set.add(file_path)
        if file_path and func_name:
            func_set.add(f"{file_path}:{func_name}")
    return file_set, func_set


def build_instance_golden_sets(inst: pd.Series, inst_id: str) -> tuple:
    if "parsed_patch" in inst and pd.notna(inst["parsed_patch"]):
        parsed_patch = ParsedPatch.model_validate_json(inst["parsed_patch"])
        return build_golden_sets(parsed_patch, inst_id)
    if "edit_functions" in inst and inst["edit_functions"] is not None:
        return build_locbench_golden_sets(inst)
    raise ValueError(
        f"Cannot build golden localization for {inst_id}: "
        "expected either parsed_patch or edit_functions."
    )


def build_model_func_candidates(loc: dict, file_path_key: str) -> List[str]:
    file_path = normalize_file_path(loc[file_path_key])
    class_name = loc["class_name"]
    method_name = loc["method_name"]
    if not (bool(class_name) or bool(method_name)):
        return []

    func = file_path + ":"
    if not class_name:
        return [func + method_name]
    if not method_name:
        return [func + class_name]
    return [func + class_name, func + class_name + "." + method_name]


def parse_output(ds_golden: pd.DataFrame, args) -> None:
    output_dir: str = args.output_dir
    artifact_dir: str = args.artifact_dir
    file_path_key: str = args.file_path_key
    file_match = 0
    func_match = 0
    notgen_cnt = 0
    # extractor_file_match = 0
    # extractor_notgen_cnt = 0
    output_dict = dict()
    issues = os.listdir(output_dir)
    golden_issues = set(ds_golden["instance_id"])
    issues = set(issues).intersection(golden_issues)
    issues = sorted(list(issues))
    file_prec_list = []
    func_prec_list = []
    file_acc_at_5_list = []
    file_f1_at_5_list = []
    func_acc_at_5_list = []
    func_f1_at_5_list = []
    inference_stats_list = []
    for inst_id in sorted(issues):
        inst = ds_golden[ds_golden["instance_id"] == inst_id].iloc[0]
        output_dict[inst_id] = dict()

        file_set, func_set = build_instance_golden_sets(inst, inst_id)
        if not file_set:
            print("No file found", inst_id)
        # if not func_set:
        #    print('No func found', inst_id)

        # is_searcher_match = False
        json_dir = f"{output_dir}/{inst_id}/searcher_{inst_id}.json"
        stats_dir = f"{output_dir}/{inst_id}/inference_stats_{inst_id}.json"
        if os.path.isfile(stats_dir):
            with open(stats_dir, "r") as handle:
                inference_stats = json.load(handle)
            output_dict[inst_id]["inference_stats"] = inference_stats
            inference_stats_list.append(inference_stats)
        # print(f"Checking {inst_id}")
        model_file_set = set()
        model_func_set = set()
        model_file_ranked = []
        model_func_ranked = []
        # print(inst_id)
        if not os.path.isfile(json_dir):
            notgen_cnt += 1
            output_dict[inst_id]["status"] = "Json not gen"
            add_missing_top_k_scores(
                file_acc_at_5_list,
                file_f1_at_5_list,
                func_acc_at_5_list,
                func_f1_at_5_list,
            )
            # print('    Json not gen')
        else:
            with open(json_dir, "r") as handle:
                model_searcher_output = json.load(handle)
            if "bug_locations" not in model_searcher_output:
                notgen_cnt += 1
                output_dict[inst_id]["status"] = "Json invalid"
                add_missing_top_k_scores(
                    file_acc_at_5_list,
                    file_f1_at_5_list,
                    func_acc_at_5_list,
                    func_f1_at_5_list,
                )
            else:
                for loc in model_searcher_output["bug_locations"]:
                    file_path = normalize_file_path(loc[file_path_key])
                    model_file_ranked.append(file_path)
                    model_file_set.add(file_path)
                    func_candidates = build_model_func_candidates(loc, file_path_key)
                    model_func_ranked.extend(func_candidates)
                    model_func_set.update(func_candidates)
                output_dict[inst_id]["file"] = dict()
                if file_set.issubset(model_file_set):
                    file_match += 1
                    output_dict[inst_id]["file"]["file_status"] = "Matched"
                else:
                    output_dict[inst_id]["file"]["file_status"] = "Not Matched"
                file_acc_at_5, file_f1_at_5 = top_k_scores(
                    file_set, model_file_ranked
                )
                file_acc_at_5_list.append(file_acc_at_5)
                file_f1_at_5_list.append(file_f1_at_5)
                file_prec_list.append(
                    len(file_set.intersection(model_file_set)) / len(model_file_set)
                    if len(model_file_set)
                    else 1
                )

                output_dict[inst_id]["file"]["golden"] = list(file_set)
                output_dict[inst_id]["file"]["model"] = unique_preserve_order(
                    model_file_ranked
                )
                output_dict[inst_id]["file"]["acc@5"] = file_acc_at_5
                output_dict[inst_id]["file"]["f1@5"] = file_f1_at_5

                output_dict[inst_id]["func"] = dict()
                if func_set.issubset(model_func_set):
                    func_match += 1

                    output_dict[inst_id]["func"]["func_status"] = "Matched"
                else:
                    output_dict[inst_id]["func"]["func_status"] = "Not Matched"
                output_dict[inst_id]["func"]["golden"] = list(func_set)
                output_dict[inst_id]["func"]["model"] = unique_preserve_order(
                    model_func_ranked
                )
                func_acc_at_5, func_f1_at_5 = top_k_scores(
                    func_set, model_func_ranked
                )
                output_dict[inst_id]["func"]["acc@5"] = func_acc_at_5
                output_dict[inst_id]["func"]["f1@5"] = func_f1_at_5
                func_acc_at_5_list.append(func_acc_at_5)
                func_f1_at_5_list.append(func_f1_at_5)
                func_prec_list.append(
                    len(func_set.intersection(model_func_set)) / len(model_func_set)
                    if len(model_func_set)
                    else 1
                )

    total_cnt = len(issues)
    metrics = {
        "num_instances": total_cnt,
        "file_match": file_match,
        "file_match_rate": file_match / total_cnt if total_cnt else 0.0,
        "mean_file_acc_at_5": safe_mean(file_acc_at_5_list),
        "std_file_acc_at_5": safe_std(file_acc_at_5_list),
        "mean_file_f1_at_5": safe_mean(file_f1_at_5_list),
        "std_file_f1_at_5": safe_std(file_f1_at_5_list),
        "mean_file_precision": safe_mean(file_prec_list),
        "std_file_precision": safe_std(file_prec_list),
        "func_match": func_match,
        "func_match_rate": func_match / total_cnt if total_cnt else 0.0,
        "mean_func_acc_at_5": safe_mean(func_acc_at_5_list),
        "std_func_acc_at_5": safe_std(func_acc_at_5_list),
        "mean_func_f1_at_5": safe_mean(func_f1_at_5_list),
        "std_func_f1_at_5": safe_std(func_f1_at_5_list),
        "mean_func_precision": safe_mean(func_prec_list),
        "std_func_precision": safe_std(func_prec_list),
        "json_not_gen": notgen_cnt,
        "json_not_gen_rate": notgen_cnt / total_cnt if total_cnt else 0.0,
    }
    if inference_stats_list:
        metrics.update(
            {
                "mean_total_tokens": safe_mean(
                    [x.get("total_tokens", 0) for x in inference_stats_list]
                ),
                "mean_input_tokens": safe_mean(
                    [x.get("in_tokens", 0) for x in inference_stats_list]
                ),
                "mean_output_tokens": safe_mean(
                    [x.get("out_tokens", 0) for x in inference_stats_list]
                ),
                "mean_wall_time_s": safe_mean(
                    [x.get("wall_time_s", 0) for x in inference_stats_list]
                ),
            }
        )

    print(f"File match: {file_match}/{total_cnt}, {metrics['file_match_rate'] * 100:.2f}%")
    if args.no_std_output:
        print(f"Mean File Acc@5: {metrics['mean_file_acc_at_5'] * 100:.2f}%")
        print(f"Mean File F1@5: {metrics['mean_file_f1_at_5'] * 100:.2f}%")
        print(f"Mean File Precision: {metrics['mean_file_precision'] * 100:.2f}%")
    else:
        print(
            f"Mean File Acc@5: {metrics['mean_file_acc_at_5'] * 100:.2f}%, Std File Acc@5: {metrics['std_file_acc_at_5'] * 100:.2f}%"
        )
        print(
            f"Mean File F1@5: {metrics['mean_file_f1_at_5'] * 100:.2f}%, Std File F1@5: {metrics['std_file_f1_at_5'] * 100:.2f}%"
        )
        print(
            f"Mean File Precision: {metrics['mean_file_precision'] * 100:.2f}%, Std File Precision: {metrics['std_file_precision'] * 100:.2f}%"
        )
    print(
        f"Function Match: {func_match}/{total_cnt}, {metrics['func_match_rate'] * 100:.2f}%"
    )
    if args.no_std_output:
        print(f"Mean Function Acc@5: {metrics['mean_func_acc_at_5'] * 100:.2f}%")
        print(f"Mean Function F1@5: {metrics['mean_func_f1_at_5'] * 100:.2f}%")
        print(f"Mean Function Precision: {metrics['mean_func_precision'] * 100:.2f}%")
    else:
        print(
            f"Mean Function Acc@5: {metrics['mean_func_acc_at_5'] * 100:.2f}%, Std Function Acc@5: {metrics['std_func_acc_at_5'] * 100:.2f}%"
        )
        print(
            f"Mean Function F1@5: {metrics['mean_func_f1_at_5'] * 100:.2f}%, Std Function F1@5: {metrics['std_func_f1_at_5'] * 100:.2f}%"
        )
        print(
            f"Mean Function Precision: {metrics['mean_func_precision'] * 100:.2f}%, Std Function Precision: {metrics['std_func_precision'] * 100:.2f}%"
        )
    print(
        f"Json not gen: {notgen_cnt}/{total_cnt}, {metrics['json_not_gen_rate'] * 100:.2f}%"
    )
    if inference_stats_list:
        print(
            f"Mean Total Tokens: {metrics['mean_total_tokens']:.2f}"
        )
        print(
            f"Mean Input Tokens: {metrics['mean_input_tokens']:.2f}"
        )
        print(
            f"Mean Output Tokens: {metrics['mean_output_tokens']:.2f}"
        )
        print(
            f"Mean Wall Time: {metrics['mean_wall_time_s']:.2f}s"
        )
    output_path = f"{artifact_dir}/assets/orcar_parsed_output.json"
    with open(output_path, "w") as handle:
        json.dump(output_dict, handle, indent=4)
    print(f"Parsed output dumped to {output_path}")
    if args.metrics_output:
        with open(args.metrics_output, "w") as handle:
            json.dump(metrics, handle, indent=4)
        print(f"Metrics dumped to {args.metrics_output}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-a",
        "--artifact_dir",
        default="./artifact",
        help=f"The directory of the artifact folder",
    )
    parser.add_argument(
        "-l",
        "--output_dir",
        default="./output",
        help=f"The directory of the output dir(agent's output)",
    )
    parser.add_argument(
        "-f",
        "--file_path_key",
        default="file_path",
        help=f"The directory of the output dir(agent's output)",
    )
    parser.add_argument(
        "-d",
        "--dataset",
        default="lite",
        help=f"The dataset to use",
    )
    parser.add_argument(
        "--split",
        default="test",
        help="Dataset split to use when loading golden data from HF.",
    )
    parser.add_argument(
        "--metrics_output",
        default=None,
        help="Optional path to dump aggregate metrics as JSON.",
    )
    parser.add_argument(
        "--no_std_output",
        action="store_true",
        help="Hide per-run std values from stdout; metrics JSON still contains them.",
    )
    args = parser.parse_args()
    ds_golden = download_golden_data(
        artifact_dir=args.artifact_dir, dataset=args.dataset, split=args.split
    )
    parse_output(ds_golden, args)


if __name__ == "__main__":
    main()
